# -*- coding: utf-8 -*-
"""gerenciador de senhas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nILp9F9e5Kz62N34bj6OMHPwAbOluG6e
"""

def gerar_senha():

  import secrets, string
  caracteres = string.ascii_letters + string.digits + string.punctuation
  tamanho = 12
  senha = ''.join(secrets.choice(caracteres) for i in range(12))

  range(tamanho)
  return senha

print("Senha gerada:", gerar_senha())